name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Logged in Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Images
      run: |
        services=("books-service" "authors-service" "reviews-service")
        
        for service in "${services[@]}"
        do
          if [ -d "$service" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:1 ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:1
          else
            echo "Failed to find the directory path for service $service"
            exit 1
          fi
        done
    - name: Clean up Previous Containers
      run: |
        docker-compose down
    - name: Execute Docker Compose
      run: |
        docker-compose up -d
  deploy-AWS:
    needs: [build-and-push]  
    runs-on: ubuntu-latest

    steps:

    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Stop and remove running containers and free ports
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} <<-EOF
          sudo docker stop service-list-task || true
          sudo docker rm service-list-task || true
          sudo docker stop service-update-task || true
          sudo docker rm service-update-task || true
          sudo docker stop service-delete-task || true
          sudo docker rm service-delete-task || true
        EOF
    
    - name: Pull Docker images
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} <<-EOF
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/books-service:1
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/authors-service:1
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reviews-service:1
        EOF
    - name: Run new containers
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} <<-EOF
          sudo docker run -d --name service-list-task -p 8085:3001 ${{ secrets.DOCKERHUB_USERNAME }}/books-service:1
          sudo docker run -d --name service-update-task -p 8084:3002 ${{ secrets.DOCKERHUB_USERNAME }}/authors-service:1
          sudo docker run -d --name service-delete-task -p 8083:3003 ${{ secrets.DOCKERHUB_USERNAME }}/reviews-service:1
        EOF